# Project
site_name: fzf404 - 分享
site_description: 给所有人的技术分享
site_author: fzf404
site_url: https://share.fzf404.art/

# Repository
repo_name: fzf404/share
edit_uri: edit/main/docs/
repo_url: https://github.com/fzf404/share

# Copyright
copyright: Copyright &copy; 2021 - 2023 By <a href="https://fzf404.art/">fzf404</a>

# Config
theme:
  language: zh
  name: material
  favicon: favicon.ico
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - content.code.copy
  palette:
    - scheme: slate
      primary: deep purple
      accent: orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      primary: deep purple
      accent: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono

# Plugin
plugins:
  - search
  - minify:
      minify_html: true

# Custom
extra:
  homepage: https:/fzf404.art/

extra_javascript:
  - assets/analysis.js

# Extension
markdown_extensions:
  - admonition
  - pymdownx.keys
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.tasklist
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite

# Page tree
nav:
  - 关于: index.md
  - 通识课:
      - 00 课程介绍: intro/00-about.md
      - 01 崭新的编辑器: intro/01-editor.md
      - 02 写个网页吧: intro/02-web.md
      - 03 覆盖全球的大网: intro/03-network.md
      - 04 程序员的社区: intro/04-community.md
      - 05 试试Python: intro/05-python.md
      - 06 产品经理登场: intro/06-product.md
      - 07 部署到服务器: intro/07-server.md
      - 08 前端的姻缘: intro/08-frontend.md
      - 09 后端的姻缘: intro/09-backend.md
      - F1 快捷键: intro/F1-shortcut.md
      - F2 初识脚本语言: intro/F2-script.md
  - 前端课:
      - 00 学习路径: web/00-intro.md
      - 01 样式库: web/01-library.md
      - 02 代码仓库: web/02-gitee.md
      
