name: gh-pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Setup
        run: pip install -r requires.txt

      - name: Deploy
        run: mkdocs gh-deploy --force
